name: BurnaAI Meme Factory

on:
  workflow_dispatch:
    inputs:
      mode:
        type: choice
        description: What to do?
        options: [generate]
        default: generate
      count:
        type: number
        description: Number of memes to generate
        default: 30
      month:
        type: number
        description: Month (1–12)
        default: 9
      year:
        type: number
        description: Year
        default: 2025
      start_day:
        type: number
        description: Start day of month for scheduling
        default: 1
      export_mode:
        type: choice
        description: Export mode for crops
        options: [blurcontain, contain, cover]
        default: blurcontain
      export_bg_hex:
        type: string
        description: Background for 'contain' (ignored for blurcontain)
        default: "#0A0F1C"

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Setup Node
        uses: actions/setup-node@v4
        with: { node-version: '20' }

      - name: Install deps
        run: npm i

      - name: Type check
        run: npx tsc --noEmit

      - name: Generate memes
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          BURNA_LOGO_PATH: ${{ vars.BURNA_LOGO_PATH }}
          EXPORT_MODE: ${{ inputs.export_mode }}
          EXPORT_BG_HEX: ${{ inputs.export_bg_hex }}
        run: |
          npx tsx src/meme-factory.ts \
            --count ${{ inputs.count }} \
            --month ${{ inputs.month }} \
            --year  ${{ inputs.year }} \
            --start-day ${{ inputs.start_day }}

      - name: Move outputs to dated folder
        shell: bash
        run: |
          set -euo pipefail
          ts=$(date +%Y-%m-%d)
          mkdir -p assets/memes
          if [ -d output ]; then
            mv output "assets/memes/${ts}"
          else
            echo "No output directory"; exit 1
          fi

      # Reframe from masters using your chosen export mode (also re-stamps logo + watermark)
      - name: Reframe/recrop outputs from masters
        env:
          BURNA_LOGO_PATH: ${{ vars.BURNA_LOGO_PATH }}
          EXPORT_MODE: ${{ inputs.export_mode }}
          EXPORT_BG_HEX: ${{ inputs.export_bg_hex }}
        run: npx tsx src/reframe.ts

      - name: Commit outputs
        shell: bash
        run: |
          set -euo pipefail
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if ! git diff --quiet; then
            git add assets/memes
            git commit -m "feat: add (or reframe) generated memes"
            git push
          else
            echo "No changes to commit."
          fi

      - name: Package latest images
        shell: bash
        run: |
          latest_dir=$(ls -1dt assets/memes/* | head -n 1)
          zip -r memes.zip "$latest_dir"
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: burna-memes
          path: memes.zip
